### ISSUE TITLE
Ciekawa biblioteka

### ISSUE THREAD

**Issue by timiTao** [Code-Mine-Development/Famil.io#2]
Masz w planach wrócić do niej? 👍

**Comment by AGmakonts** [comment]
Hej, wybacz delay, dopiero zobaczyłem issue :) W wolnej chwili na pewno

**Comment by timiTao** [comment]
Dalej nieokreślona przyszłość? 
Zaciekawiło mnie modelowanie i budowanie zależności między obiektami - dokąd zmierzasz Panie? 👍

**Comment by AGmakonts** [comment]
Generalnie przydałby się mały refaktor, zwłaszcza by pozbyć sie biblioteki STL, Jak znajdę chwilę, może w lutym to coś jeszcze podziałam
